/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as FreischaltenImport } from './routes/freischalten'
import { Route as EinladungImport } from './routes/einladung'
import { Route as OnboardingRouteImport } from './routes/onboarding/route'
import { Route as AuthRouteImport } from './routes/_auth/route'
import { Route as IndexImport } from './routes/index'
import { Route as OnboardingSchuleImport } from './routes/onboarding/schule'
import { Route as OnboardingPersonalImport } from './routes/onboarding/personal'
import { Route as AuthAccountImport } from './routes/_auth/account'
import { Route as AuthVorschauIndexImport } from './routes/_auth/vorschau.index'
import { Route as AuthOrderIndexImport } from './routes/_auth/order.index'
import { Route as AuthHomeIndexImport } from './routes/_auth/home.index'
import { Route as AuthVorschauImageIdIndexImport } from './routes/_auth/vorschau.$imageId.index'
import { Route as AuthVorschauImageIdVerbessernImport } from './routes/_auth/vorschau.$imageId.verbessern'
import { Route as AuthOrderOrderIdDesignerIndexImport } from './routes/_auth/order.$orderId.designer.index'
import { Route as AuthOrderOrderIdDesignerDesignIdRouteImport } from './routes/_auth/order.$orderId.designer.$designId.route'
import { Route as AuthOrderOrderIdDesignerDesignIdPulloverImport } from './routes/_auth/order.$orderId.designer.$designId.pullover'
import { Route as AuthOrderOrderIdDesignerDesignIdImagesImport } from './routes/_auth/order.$orderId.designer.$designId.images'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const FreischaltenRoute = FreischaltenImport.update({
  id: '/freischalten',
  path: '/freischalten',
  getParentRoute: () => rootRoute,
} as any)

const EinladungRoute = EinladungImport.update({
  id: '/einladung',
  path: '/einladung',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingRouteRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingSchuleRoute = OnboardingSchuleImport.update({
  id: '/schule',
  path: '/schule',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const OnboardingPersonalRoute = OnboardingPersonalImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => OnboardingRouteRoute,
} as any)

const AuthAccountRoute = AuthAccountImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthVorschauIndexRoute = AuthVorschauIndexImport.update({
  id: '/vorschau/',
  path: '/vorschau/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthOrderIndexRoute = AuthOrderIndexImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthHomeIndexRoute = AuthHomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthVorschauImageIdIndexRoute = AuthVorschauImageIdIndexImport.update({
  id: '/vorschau/$imageId/',
  path: '/vorschau/$imageId/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthVorschauImageIdVerbessernRoute =
  AuthVorschauImageIdVerbessernImport.update({
    id: '/vorschau/$imageId/verbessern',
    path: '/vorschau/$imageId/verbessern',
    getParentRoute: () => AuthRouteRoute,
  } as any)

const AuthOrderOrderIdDesignerIndexRoute =
  AuthOrderOrderIdDesignerIndexImport.update({
    id: '/order/$orderId/designer/',
    path: '/order/$orderId/designer/',
    getParentRoute: () => AuthRouteRoute,
  } as any)

const AuthOrderOrderIdDesignerDesignIdRouteRoute =
  AuthOrderOrderIdDesignerDesignIdRouteImport.update({
    id: '/order/$orderId/designer/$designId',
    path: '/order/$orderId/designer/$designId',
    getParentRoute: () => AuthRouteRoute,
  } as any)

const AuthOrderOrderIdDesignerDesignIdPulloverRoute =
  AuthOrderOrderIdDesignerDesignIdPulloverImport.update({
    id: '/pullover',
    path: '/pullover',
    getParentRoute: () => AuthOrderOrderIdDesignerDesignIdRouteRoute,
  } as any)

const AuthOrderOrderIdDesignerDesignIdImagesRoute =
  AuthOrderOrderIdDesignerDesignIdImagesImport.update({
    id: '/images',
    path: '/images',
    getParentRoute: () => AuthOrderOrderIdDesignerDesignIdRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRoute
    }
    '/einladung': {
      id: '/einladung'
      path: '/einladung'
      fullPath: '/einladung'
      preLoaderRoute: typeof EinladungImport
      parentRoute: typeof rootRoute
    }
    '/freischalten': {
      id: '/freischalten'
      path: '/freischalten'
      fullPath: '/freischalten'
      preLoaderRoute: typeof FreischaltenImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/account': {
      id: '/_auth/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthAccountImport
      parentRoute: typeof AuthRouteImport
    }
    '/onboarding/personal': {
      id: '/onboarding/personal'
      path: '/personal'
      fullPath: '/onboarding/personal'
      preLoaderRoute: typeof OnboardingPersonalImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/onboarding/schule': {
      id: '/onboarding/schule'
      path: '/schule'
      fullPath: '/onboarding/schule'
      preLoaderRoute: typeof OnboardingSchuleImport
      parentRoute: typeof OnboardingRouteImport
    }
    '/_auth/home/': {
      id: '/_auth/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthHomeIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/order/': {
      id: '/_auth/order/'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof AuthOrderIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/vorschau/': {
      id: '/_auth/vorschau/'
      path: '/vorschau'
      fullPath: '/vorschau'
      preLoaderRoute: typeof AuthVorschauIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/vorschau/$imageId/verbessern': {
      id: '/_auth/vorschau/$imageId/verbessern'
      path: '/vorschau/$imageId/verbessern'
      fullPath: '/vorschau/$imageId/verbessern'
      preLoaderRoute: typeof AuthVorschauImageIdVerbessernImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/vorschau/$imageId/': {
      id: '/_auth/vorschau/$imageId/'
      path: '/vorschau/$imageId'
      fullPath: '/vorschau/$imageId'
      preLoaderRoute: typeof AuthVorschauImageIdIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/order/$orderId/designer/$designId': {
      id: '/_auth/order/$orderId/designer/$designId'
      path: '/order/$orderId/designer/$designId'
      fullPath: '/order/$orderId/designer/$designId'
      preLoaderRoute: typeof AuthOrderOrderIdDesignerDesignIdRouteImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/order/$orderId/designer/': {
      id: '/_auth/order/$orderId/designer/'
      path: '/order/$orderId/designer'
      fullPath: '/order/$orderId/designer'
      preLoaderRoute: typeof AuthOrderOrderIdDesignerIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/_auth/order/$orderId/designer/$designId/images': {
      id: '/_auth/order/$orderId/designer/$designId/images'
      path: '/images'
      fullPath: '/order/$orderId/designer/$designId/images'
      preLoaderRoute: typeof AuthOrderOrderIdDesignerDesignIdImagesImport
      parentRoute: typeof AuthOrderOrderIdDesignerDesignIdRouteImport
    }
    '/_auth/order/$orderId/designer/$designId/pullover': {
      id: '/_auth/order/$orderId/designer/$designId/pullover'
      path: '/pullover'
      fullPath: '/order/$orderId/designer/$designId/pullover'
      preLoaderRoute: typeof AuthOrderOrderIdDesignerDesignIdPulloverImport
      parentRoute: typeof AuthOrderOrderIdDesignerDesignIdRouteImport
    }
  }
}

// Create and export the route tree

interface AuthOrderOrderIdDesignerDesignIdRouteRouteChildren {
  AuthOrderOrderIdDesignerDesignIdImagesRoute: typeof AuthOrderOrderIdDesignerDesignIdImagesRoute
  AuthOrderOrderIdDesignerDesignIdPulloverRoute: typeof AuthOrderOrderIdDesignerDesignIdPulloverRoute
}

const AuthOrderOrderIdDesignerDesignIdRouteRouteChildren: AuthOrderOrderIdDesignerDesignIdRouteRouteChildren =
  {
    AuthOrderOrderIdDesignerDesignIdImagesRoute:
      AuthOrderOrderIdDesignerDesignIdImagesRoute,
    AuthOrderOrderIdDesignerDesignIdPulloverRoute:
      AuthOrderOrderIdDesignerDesignIdPulloverRoute,
  }

const AuthOrderOrderIdDesignerDesignIdRouteRouteWithChildren =
  AuthOrderOrderIdDesignerDesignIdRouteRoute._addFileChildren(
    AuthOrderOrderIdDesignerDesignIdRouteRouteChildren,
  )

interface AuthRouteRouteChildren {
  AuthAccountRoute: typeof AuthAccountRoute
  AuthHomeIndexRoute: typeof AuthHomeIndexRoute
  AuthOrderIndexRoute: typeof AuthOrderIndexRoute
  AuthVorschauIndexRoute: typeof AuthVorschauIndexRoute
  AuthVorschauImageIdVerbessernRoute: typeof AuthVorschauImageIdVerbessernRoute
  AuthVorschauImageIdIndexRoute: typeof AuthVorschauImageIdIndexRoute
  AuthOrderOrderIdDesignerDesignIdRouteRoute: typeof AuthOrderOrderIdDesignerDesignIdRouteRouteWithChildren
  AuthOrderOrderIdDesignerIndexRoute: typeof AuthOrderOrderIdDesignerIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAccountRoute: AuthAccountRoute,
  AuthHomeIndexRoute: AuthHomeIndexRoute,
  AuthOrderIndexRoute: AuthOrderIndexRoute,
  AuthVorschauIndexRoute: AuthVorschauIndexRoute,
  AuthVorschauImageIdVerbessernRoute: AuthVorschauImageIdVerbessernRoute,
  AuthVorschauImageIdIndexRoute: AuthVorschauImageIdIndexRoute,
  AuthOrderOrderIdDesignerDesignIdRouteRoute:
    AuthOrderOrderIdDesignerDesignIdRouteRouteWithChildren,
  AuthOrderOrderIdDesignerIndexRoute: AuthOrderOrderIdDesignerIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingPersonalRoute: typeof OnboardingPersonalRoute
  OnboardingSchuleRoute: typeof OnboardingSchuleRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingPersonalRoute: OnboardingPersonalRoute,
  OnboardingSchuleRoute: OnboardingSchuleRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/einladung': typeof EinladungRoute
  '/freischalten': typeof FreischaltenRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthAccountRoute
  '/onboarding/personal': typeof OnboardingPersonalRoute
  '/onboarding/schule': typeof OnboardingSchuleRoute
  '/home': typeof AuthHomeIndexRoute
  '/order': typeof AuthOrderIndexRoute
  '/vorschau': typeof AuthVorschauIndexRoute
  '/vorschau/$imageId/verbessern': typeof AuthVorschauImageIdVerbessernRoute
  '/vorschau/$imageId': typeof AuthVorschauImageIdIndexRoute
  '/order/$orderId/designer/$designId': typeof AuthOrderOrderIdDesignerDesignIdRouteRouteWithChildren
  '/order/$orderId/designer': typeof AuthOrderOrderIdDesignerIndexRoute
  '/order/$orderId/designer/$designId/images': typeof AuthOrderOrderIdDesignerDesignIdImagesRoute
  '/order/$orderId/designer/$designId/pullover': typeof AuthOrderOrderIdDesignerDesignIdPulloverRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/einladung': typeof EinladungRoute
  '/freischalten': typeof FreischaltenRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthAccountRoute
  '/onboarding/personal': typeof OnboardingPersonalRoute
  '/onboarding/schule': typeof OnboardingSchuleRoute
  '/home': typeof AuthHomeIndexRoute
  '/order': typeof AuthOrderIndexRoute
  '/vorschau': typeof AuthVorschauIndexRoute
  '/vorschau/$imageId/verbessern': typeof AuthVorschauImageIdVerbessernRoute
  '/vorschau/$imageId': typeof AuthVorschauImageIdIndexRoute
  '/order/$orderId/designer/$designId': typeof AuthOrderOrderIdDesignerDesignIdRouteRouteWithChildren
  '/order/$orderId/designer': typeof AuthOrderOrderIdDesignerIndexRoute
  '/order/$orderId/designer/$designId/images': typeof AuthOrderOrderIdDesignerDesignIdImagesRoute
  '/order/$orderId/designer/$designId/pullover': typeof AuthOrderOrderIdDesignerDesignIdPulloverRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/einladung': typeof EinladungRoute
  '/freischalten': typeof FreischaltenRoute
  '/login': typeof LoginRoute
  '/_auth/account': typeof AuthAccountRoute
  '/onboarding/personal': typeof OnboardingPersonalRoute
  '/onboarding/schule': typeof OnboardingSchuleRoute
  '/_auth/home/': typeof AuthHomeIndexRoute
  '/_auth/order/': typeof AuthOrderIndexRoute
  '/_auth/vorschau/': typeof AuthVorschauIndexRoute
  '/_auth/vorschau/$imageId/verbessern': typeof AuthVorschauImageIdVerbessernRoute
  '/_auth/vorschau/$imageId/': typeof AuthVorschauImageIdIndexRoute
  '/_auth/order/$orderId/designer/$designId': typeof AuthOrderOrderIdDesignerDesignIdRouteRouteWithChildren
  '/_auth/order/$orderId/designer/': typeof AuthOrderOrderIdDesignerIndexRoute
  '/_auth/order/$orderId/designer/$designId/images': typeof AuthOrderOrderIdDesignerDesignIdImagesRoute
  '/_auth/order/$orderId/designer/$designId/pullover': typeof AuthOrderOrderIdDesignerDesignIdPulloverRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/onboarding'
    | '/einladung'
    | '/freischalten'
    | '/login'
    | '/account'
    | '/onboarding/personal'
    | '/onboarding/schule'
    | '/home'
    | '/order'
    | '/vorschau'
    | '/vorschau/$imageId/verbessern'
    | '/vorschau/$imageId'
    | '/order/$orderId/designer/$designId'
    | '/order/$orderId/designer'
    | '/order/$orderId/designer/$designId/images'
    | '/order/$orderId/designer/$designId/pullover'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/onboarding'
    | '/einladung'
    | '/freischalten'
    | '/login'
    | '/account'
    | '/onboarding/personal'
    | '/onboarding/schule'
    | '/home'
    | '/order'
    | '/vorschau'
    | '/vorschau/$imageId/verbessern'
    | '/vorschau/$imageId'
    | '/order/$orderId/designer/$designId'
    | '/order/$orderId/designer'
    | '/order/$orderId/designer/$designId/images'
    | '/order/$orderId/designer/$designId/pullover'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/onboarding'
    | '/einladung'
    | '/freischalten'
    | '/login'
    | '/_auth/account'
    | '/onboarding/personal'
    | '/onboarding/schule'
    | '/_auth/home/'
    | '/_auth/order/'
    | '/_auth/vorschau/'
    | '/_auth/vorschau/$imageId/verbessern'
    | '/_auth/vorschau/$imageId/'
    | '/_auth/order/$orderId/designer/$designId'
    | '/_auth/order/$orderId/designer/'
    | '/_auth/order/$orderId/designer/$designId/images'
    | '/_auth/order/$orderId/designer/$designId/pullover'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  EinladungRoute: typeof EinladungRoute
  FreischaltenRoute: typeof FreischaltenRoute
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  EinladungRoute: EinladungRoute,
  FreischaltenRoute: FreischaltenRoute,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/onboarding",
        "/einladung",
        "/freischalten",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth/route.tsx",
      "children": [
        "/_auth/account",
        "/_auth/home/",
        "/_auth/order/",
        "/_auth/vorschau/",
        "/_auth/vorschau/$imageId/verbessern",
        "/_auth/vorschau/$imageId/",
        "/_auth/order/$orderId/designer/$designId",
        "/_auth/order/$orderId/designer/"
      ]
    },
    "/onboarding": {
      "filePath": "onboarding/route.tsx",
      "children": [
        "/onboarding/personal",
        "/onboarding/schule"
      ]
    },
    "/einladung": {
      "filePath": "einladung.tsx"
    },
    "/freischalten": {
      "filePath": "freischalten.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/account": {
      "filePath": "_auth/account.tsx",
      "parent": "/_auth"
    },
    "/onboarding/personal": {
      "filePath": "onboarding/personal.tsx",
      "parent": "/onboarding"
    },
    "/onboarding/schule": {
      "filePath": "onboarding/schule.tsx",
      "parent": "/onboarding"
    },
    "/_auth/home/": {
      "filePath": "_auth/home.index.tsx",
      "parent": "/_auth"
    },
    "/_auth/order/": {
      "filePath": "_auth/order.index.tsx",
      "parent": "/_auth"
    },
    "/_auth/vorschau/": {
      "filePath": "_auth/vorschau.index.tsx",
      "parent": "/_auth"
    },
    "/_auth/vorschau/$imageId/verbessern": {
      "filePath": "_auth/vorschau.$imageId.verbessern.tsx",
      "parent": "/_auth"
    },
    "/_auth/vorschau/$imageId/": {
      "filePath": "_auth/vorschau.$imageId.index.tsx",
      "parent": "/_auth"
    },
    "/_auth/order/$orderId/designer/$designId": {
      "filePath": "_auth/order.$orderId.designer.$designId.route.tsx",
      "parent": "/_auth",
      "children": [
        "/_auth/order/$orderId/designer/$designId/images",
        "/_auth/order/$orderId/designer/$designId/pullover"
      ]
    },
    "/_auth/order/$orderId/designer/": {
      "filePath": "_auth/order.$orderId.designer.index.tsx",
      "parent": "/_auth"
    },
    "/_auth/order/$orderId/designer/$designId/images": {
      "filePath": "_auth/order.$orderId.designer.$designId.images.tsx",
      "parent": "/_auth/order/$orderId/designer/$designId"
    },
    "/_auth/order/$orderId/designer/$designId/pullover": {
      "filePath": "_auth/order.$orderId.designer.$designId.pullover.tsx",
      "parent": "/_auth/order/$orderId/designer/$designId"
    }
  }
}
ROUTE_MANIFEST_END */
