/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TestingImport } from './routes/testing'
import { Route as LoginImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth/route'
import { Route as AdminRouteImport } from './routes/_admin/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthOrdersImport } from './routes/_auth/orders'
import { Route as AuthDesignerOrderIdImport } from './routes/_auth/designer.$orderId'
import { Route as AdminAdminOrdersImport } from './routes/_admin/admin.orders'

// Create/Update Routes

const TestingRoute = TestingImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRouteRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AdminRouteRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthOrdersRoute = AuthOrdersImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthDesignerOrderIdRoute = AuthDesignerOrderIdImport.update({
  id: '/designer/$orderId',
  path: '/designer/$orderId',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AdminAdminOrdersRoute = AdminAdminOrdersImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/testing': {
      id: '/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof TestingImport
      parentRoute: typeof rootRoute
    }
    '/_auth/orders': {
      id: '/_auth/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthOrdersImport
      parentRoute: typeof AuthRouteImport
    }
    '/_admin/admin/orders': {
      id: '/_admin/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAdminOrdersImport
      parentRoute: typeof AdminRouteImport
    }
    '/_auth/designer/$orderId': {
      id: '/_auth/designer/$orderId'
      path: '/designer/$orderId'
      fullPath: '/designer/$orderId'
      preLoaderRoute: typeof AuthDesignerOrderIdImport
      parentRoute: typeof AuthRouteImport
    }
  }
}

// Create and export the route tree

interface AdminRouteRouteChildren {
  AdminAdminOrdersRoute: typeof AdminAdminOrdersRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminOrdersRoute: AdminAdminOrdersRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthOrdersRoute: typeof AuthOrdersRoute
  AuthDesignerOrderIdRoute: typeof AuthDesignerOrderIdRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthOrdersRoute: AuthOrdersRoute,
  AuthDesignerOrderIdRoute: AuthDesignerOrderIdRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/testing': typeof TestingRoute
  '/orders': typeof AuthOrdersRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/designer/$orderId': typeof AuthDesignerOrderIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/testing': typeof TestingRoute
  '/orders': typeof AuthOrdersRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/designer/$orderId': typeof AuthDesignerOrderIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/testing': typeof TestingRoute
  '/_auth/orders': typeof AuthOrdersRoute
  '/_admin/admin/orders': typeof AdminAdminOrdersRoute
  '/_auth/designer/$orderId': typeof AuthDesignerOrderIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/testing'
    | '/orders'
    | '/admin/orders'
    | '/designer/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/testing'
    | '/orders'
    | '/admin/orders'
    | '/designer/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_auth'
    | '/login'
    | '/testing'
    | '/_auth/orders'
    | '/_admin/admin/orders'
    | '/_auth/designer/$orderId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  TestingRoute: typeof TestingRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  TestingRoute: TestingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_admin",
        "/_auth",
        "/login",
        "/testing"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_admin": {
      "filePath": "_admin/route.tsx",
      "children": [
        "/_admin/admin/orders"
      ]
    },
    "/_auth": {
      "filePath": "_auth/route.tsx",
      "children": [
        "/_auth/orders",
        "/_auth/designer/$orderId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/testing": {
      "filePath": "testing.tsx"
    },
    "/_auth/orders": {
      "filePath": "_auth/orders.tsx",
      "parent": "/_auth"
    },
    "/_admin/admin/orders": {
      "filePath": "_admin/admin.orders.tsx",
      "parent": "/_admin"
    },
    "/_auth/designer/$orderId": {
      "filePath": "_auth/designer.$orderId.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
